name: ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Run tests
        run: go list -f '{{.Dir}}/...' -m | xargs go test

  build-fsbp-fix:
    name: Build fsbp-fix
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run build
        uses: ./.github/actions/build
        with:
          APP: fsbp-fix
          GO_VERSION: ${{ env.GO_VERSION }}

  commit-lint:
    runs-on: ubuntu-latest
    name: Run Commitlint
    steps:
      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@9c112b70de7b0e51f81d12a5268a451db5419794 # v2.0.0

  enforce-dashes:
    name: Enforce dashes in project names
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint fsbp-fix
        run: ./script/dash-lint.sh fsbp-fix

  release:
    name: Create GitHub release
    permissions:
      contents: write
      packages: write
      issues: write
    needs: [build-fsbp-fix, commit-lint, enforce-dashes]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          # See https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md
          node-version: "22.14.0"
    
      - name: Fetch build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifact-fsbp-fix
          path: release

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
