name: ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache: false

      - name: Run tests
        run: go list -f '{{.Dir}}/...' -m | xargs go test

  build-fsbp-fix:
    name: Build fsbp-fix
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run build
        uses: ./.github/actions/build
        with:
          APP: fsbp-fix
          GO_VERSION: ${{ env.GO_VERSION }}

  commit-lint:
    runs-on: ubuntu-latest
    name: Run Commitlint
    steps:
      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@02e7ff4f7f1e4b1f8e2955b114bfa9271f1c7c97 # v1.3.0

  enforce-dashes:
    name: Enforce dashes in project names
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Lint fsbp-fix
        run: ./script/dash-lint.sh fsbp-fix

  release:
    name: Create GitHub release
    permissions:
      contents: write
      packages: write
      issues: write
    needs: [build-fsbp-fix, commit-lint, enforce-dashes]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          # See https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md
          node-version: "20.14.0"

      - name: Fetch build
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: artifact-fsbp-fix
          path: release

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
